[package]
name = "program_config_derive"
version = "0.1.0"
authors = ["Dylan Reid <dgreid@chromium.org>"]
edition = "2018"

[dependencies]
getopts = "0.2.21"
quote = "1.0"
proc-macro2 = "1.0"

[dependencies.syn]
version = "*"
features = ["full"]

[lib]
proc-macro = true
